### PR TITLE
Add group 68 files.

### PR DESCRIPTION
**Pull request by shossains**

### CODE REVIEW

**Comment by yangelova** [comment]
Hey, there is a merge conflict in the `package-lock.json` file. Could you resolve it such that your MR can be merged?

**Comment by shossains** [comment]
Hi, I resolved it and added a missing repo link as well

**Comment by yangelova** [comment]
Hello, the conflicts have not been resolved and certain files are now duplicated. Please make sure that your MR does not modify in any way files that are not part of your group's information.

**Comment by shossains** [comment]
Third time's a charm? Some file now appear modified but are actually identical to that of the dev branch (eg. readme, create_a_new_student)

**Pull request closed without merging**
