### PR TITLE
Add Group 36 files.

### PR DESCRIPTION
**Pull request by jgroenheide**
Getting it all set up was quite a struggle, so I hope everything is as it should be.

### CODE REVIEW

**Comment by yangelova** [comment]
Hey, there is a merge conflict in the `package-lock.json` file. Could you resolve it such that your MR can be merged?

**Comment by yangelova** [comment]
I'm sorry could you please exclude the `package-lock.json` from your MR? Then everything will be correct.

**Comment by jgroenheide** [comment]
How can I remove the file from the MR? Do I add it to the `.gitignore`, or is there another way?

**Comment by yangelova** [comment]
There other ways to do it using git commands. You **should not** add it to the `.gitignore`, but rather change your own commit.

**Comment by jgroenheide** [comment]
I feel like it will be easiest to close this PR and go through the process again to create a new request without the `package-lock.json` merge conflict.

**Comment by yangelova** [comment]
Sure! I'll close this one and you can make a new one with only your group's files

**Pull request closed without merging**
